import type { Metadata } from 'next'
import '@/app/(frontend)/styles/globals.css'
import NavBar from '@/components/NavBar'
import { GeistSans } from 'geist/font/sans'
import SmoothScrolling from '@/components/SmoothScrolling'
import Footer from '@/components/Footer'
import { getPayloadHMR } from '@payloadcms/next/utilities'
import configPromise from '@payload-config'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const payload = await getPayloadHMR({ config: configPromise })
  const header = (await payload.findGlobal({ slug: 'header' })) as any
  const settings = (await payload.findGlobal({ slug: 'settings' })) as any

  return (
    <html lang="es" className={GeistSans.className}>
      <body className="overflow-x-hidden twAply">
        <SmoothScrolling>
          <NavBar data={header.navMenu} />
          {children}
          <Footer></Footer>
        </SmoothScrolling>
      </body>
    </html>
  )
}
