import type { Metadata } from 'next'
import '@/app/(frontend)/styles/globals.css'
import NavBar from '@/components/NavBar'
import { GeistSans } from 'geist/font/sans'
import SmoothScrolling from '@/components/SmoothScrolling'
import Footer from '@/components/Footer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="es" className={GeistSans.className}>
      <body className="overflow-x-hidden">
        <NavBar />
        {children}
        <Footer></Footer>
      </body>
    </html>
  )
}
