import type { Metadata } from 'next'
import '@/app/(frontend)/styles/globals.css'
import NavBar from '@/components/NavBar'
import SmoothScrolling from '@/components/SmoothScrolling'
import Footer from '@/components/Footer'
import { getPayloadHMR } from '@payloadcms/next/utilities'
import configPromise from '@payload-config'
import localFont from 'next/font/local'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const SequelSans = localFont({
  src: [
    {
      path: '../fonts/GeistVF.woff2',
    },
  ],
  variable: '--font-SequelSans',
})
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const payload = await getPayloadHMR({ config: configPromise })
  const header = (await payload.findGlobal({ slug: 'header' })) as any
  const settings = (await payload.findGlobal({ slug: 'settings' })) as any

  return (
    <html lang="es" className={`${SequelSans.variable}`}>
      <body className="overflow-x-hidden useTw bg-[#f8f8f8]">
        <SmoothScrolling>
          <NavBar data={header.navMenu} />
          {children}
          <Footer></Footer>
        </SmoothScrolling>
      </body>
    </html>
  )
}
